function dph = rhs_K2d1(ph, m, omega, alpha)
%compute P^{2,1}, as defined in the paper.
% if N is large this function is faster than "rhs_K2d1_slow", but the result is the same.

Z = mean(exp((1:3).*1i.*ph), 1);
r = abs(Z);
ang = angle(Z);

%the following formulas are copied from mathematica. (see mathematica notebook in this github repository).

%blue
dph1 = (-2).*m.*cos(2.*alpha+(-1).*ph)+(-3).*m.*cos(ph)+3.*m.*cos(2.*ph+( ...
  -1).*ang(1)).*r(1)+(-2).*m.*cos(ang(1)).*r(1)+(-3).*m.*cos(2.* ...
  alpha+ang(1)).*r(1)+2.*m.*cos(2.*alpha+(-2).*ph+ang(1)).*r(1)+2.* ...
  m.*cos(2.*alpha+(-1).*ph).*r(1).^2+2.*m.*cos(ph).*r(1).^2+(-2).* ...
  m.*cos(2.*alpha+(-3).*ph+2.*ang(1)).*r(1).^2+2.*m.*cos(ph+(-1).* ...
  ang(2)).*r(2)+4.*m.*cos(2.*alpha+(-1).*ph+ang(2)).*r(2)+m.*cos( ...
  ang(1)+(-1).*ang(2)).*r(1).*r(2)+(-1).*m.*cos(2.*alpha+(-2).*ph+ ...
  ang(1)+ang(2)).*r(1).*r(2)+(-1).*m.*cos(ph).*r(2).^2+(-2).*m.*cos( ...
  ph+ang(1)+(-1).*ang(3)).*r(1).*r(3)+(-2).*omega.*sin(2.*alpha+(-1) ...
  .*ph)+2.*omega.*r(1).^2.*sin(2.*alpha+(-1).*ph)+3.*omega.*sin(ph)+ ...
  (-2).*omega.*r(1).^2.*sin(ph)+omega.*r(2).^2.*sin(ph)+(-3).* ...
  omega.*r(1).*sin(2.*ph+(-1).*ang(1))+2.*omega.*r(1).*sin(ang(1))+ ...
  3.*omega.*r(1).*sin(2.*alpha+ang(1))+2.*omega.*r(1).*sin(2.*alpha+ ...
  (-2).*ph+ang(1))+(-2).*omega.*r(1).^2.*sin(2.*alpha+(-3).*ph+2.* ...
  ang(1))+2.*omega.*r(2).*sin(ph+(-1).*ang(2))+omega.*r(1).*r(2).* ...
  sin(ang(1)+(-1).*ang(2))+(-4).*omega.*r(2).*sin(2.*alpha+(-1).*ph+ ...
  ang(2))+omega.*r(1).*r(2).*sin(2.*alpha+(-2).*ph+ang(1)+ang(2))+( ...
  -2).*omega.*r(1).*r(3).*sin(ph+ang(1)+(-1).*ang(3));

fct1 = 1/(4*(m^2+omega^2));
dph1 = dph1*fct1;

%green
dph2 = cos(ang(1)).*r(1)+(-1).*cos(2.*alpha+ang(1)).*r(1)+2.*cos(2.* ...
  alpha+(-2).*ph+ang(1)).*r(1)+(-1).*cos(2.*alpha+(-1).*ph).*r(1) ...
  .^2+(-1).*cos(ph).*r(1).^2+(-1).*cos(2.*alpha+(-3).*ph+2.*ang(1)) ...
  .*r(1).^2+2.*cos(2.*alpha+(-1).*ph+2.*ang(1)).*r(1).^2+(-2).*cos( ...
  ang(1)+(-1).*ang(2)).*r(1).*r(2)+cos(2.*ph+ang(1)+(-1).*ang(2)).* ...
  r(1).*r(2)+(-1).*cos(2.*alpha+(-2).*ph+ang(1)+ang(2)).*r(1).*r(2)+ ...
  cos(ph+ang(1)+(-1).*ang(3)).*r(1).*r(3);

fct2 = 1/(4*m);
dph2 = dph2*fct2;

dph = dph1+dph2;
    
end